name: 03. Orchestrate r36.3.0 pipeline

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: orchestrate-r3630-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dispatch-sequence:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PyTorch r36.3.0
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3630-pytorch.yml
          ref: main
          label: Build PyTorch r36.3.0

      - name: Build ROS Humble Core r36.3.0
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3630-humblecore.yml
          ref: main
          label: Build ROS Humble Core r36.3.0

      - name: Build ROS Humble Base r36.3.0
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3630-humblebase.yml
          ref: main
          label: Build ROS Humble Base r36.3.0

      - name: Build ROS + PyTorch Humble Core r36.3.0
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3630-pytorch-humblecore.yml
          ref: main
          label: Build ROS + PyTorch Humble Core r36.3.0
